# Packit configuration for automated COPR builds
# See: https://packit.dev/docs/configuration
#
# This config uses vendored source tarballs from GitHub Releases.
# The release workflow creates the tarball, then Packit triggers on release.

specfile_path: teleddns.spec
upstream_tag_template: v{version}

# Download source tarball from GitHub Releases (created by release workflow)
# The URL is defined in teleddns.spec Source0
# Note: All release tarballs include vendored dependencies for offline builds
sources:
  - path: teleddns-{version}.tar.gz
    url: https://github.com/tmshlvck/teleddns/releases/download/v{version}/teleddns-{version}.tar.gz

# Don't create archive from git - use the downloaded vendored tarball
actions:
  create-archive:
    - bash -c "echo 'Using vendored tarball from GitHub Releases'"

jobs:
  # Build in COPR on new GitHub releases (after release workflow creates tarball)
  - job: copr_build
    trigger: release
    owner: tmshlvck
    project: teleddns
    targets:
      - fedora-stable
      - fedora-development
